services:
  nginx:
    image: nginx:alpine
    build: !reset null
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./downloads:/var/www/download:ro

  backend:
    environment:
      NODE_ENV: production
      FRONTEND_URL: https://curioustide.no

  frontend:
    environment:
      VITE_LIVEKIT_URL: wss://curioustide.no/livekit

  livekit:
    volumes:
      - ./livekit/livekit.prod.yaml:/etc/livekit/livekit.yaml:ro
